competitions/urls.py
from django.urls import path

from . import views

app_name = 'competitions'
urlpatterns = [
    path('', views.CompetitionListView.as_view(), name='index'),
    path('<int:pk>/', views.CompetitionDetailView.as_view(), name='detail'),
    path('search/', views.search_competitions, name='search'),
    path('create/', views.CompetitionCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.CompetitionUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.CompetitionDeleteView.as_view(), name='delete'),

]

soccersite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('staticpages.urls')),
    path('teams/', include('teams.urls')),
    path('competitions/', include('competitions.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
    document_root=settings.MEDIA_ROOT)

teams/urls.py
from django.urls import path

from . import views

app_name = 'teams'
urlpatterns = [
    path('', views.TeamListView.as_view(), name='index'),
    path('<int:pk>/', views.TeamDetailView.as_view(), name='detail'), 
    path('search/', views.search_teams, name='search'),
    path('create/', views.TeamCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.TeamUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.TeamDeleteView.as_view(), name='delete'),
    path('<int:pk>/comment/', views.post_comment, name='comment'),
]

teams/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.urls import reverse

# Create your models here.
class Team(models.Model):
    post_date    = models.DateTimeField(default = timezone.now)
    name         = models.CharField(max_length=100)
    full_name    = models.CharField(max_length=100)        
    logo_url     = models.URLField(max_length=500, null=True)
    foundation   = models.IntegerField()
    base_city    = models.CharField(max_length=100)
    country      = models.CharField(max_length=100)
    about        = models.TextField(default="")

    def get_absolute_url(self):
        return reverse("teams:detail", kwargs={"pk": self.pk})
    
    def __str__(self):
        return f'{self.name}'    

class Comment(models.Model):
    post_date  = models.DateTimeField(default = timezone.now)
    author     = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text       = models.TextField(max_length=255)
    likes      = models.IntegerField(default=0)
    team       = models.ForeignKey(Team, related_name="comments", on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse("teams:detail", kwargs={"pk": self.team.pk})

    def __str__(self):
        return f'{self.author.username} - "{self.text}"'

teams/forms.py
from django.forms import ModelForm, ModelMultipleChoiceField
from .models import Team, Comment
from competitions.models import Competition

class TeamForm(ModelForm):
    class Meta:
        model = Team
        fields = [
            'name',
            'full_name',
            'logo_url',
            'foundation',
            'base_city',
            'country',
            'about',
        ]
        labels = {
            'name' : 'Nome da equipe',
            'full_name': 'Nome completo da equipe',
            'logo_url' : 'URL do escudo',
            'foundation' : 'Ano de fundação',
            'base_city' : 'Cidade sede',
            'country' : 'País',
            'about' : 'Sobre a equipe',
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Autor',
            'text': 'Comentário',
        }

teams/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, fields
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView 

from .models import Team, Comment
from .forms import TeamForm, CommentForm

# Create your views here.

def search_teams(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        team_list = Team.objects.filter(Q(name__icontains=search_term) | Q(country__icontains=search_term) )
        context = {"team_list": team_list}
    return render(request, 'teams/search.html', context)

class TeamDetailView(DetailView):
    model = Team
    template_name = 'teams/detail.html'
    queryset = model.objects.all()
    
    def get_object(self):
        team_id = self.kwargs.get("pk")
        return get_object_or_404(Team, pk=team_id)

class TeamListView(ListView):
    model = Team
    template_name = 'teams/index.html'
    queryset = model.objects.all()

class TeamCreateView(CreateView):
    model = Team
    template_name = 'teams/create.html'
    form_class = TeamForm
    queryset = model.objects.all()

    def form_valid(self, form):
        return super().form_valid(form)

class TeamUpdateView(UpdateView):
    model = Team
    template_name = 'teams/update.html'
    form_class = TeamForm
    queryset = model.objects.all()

    def form_valid(self, form):
        return super().form_valid(form)
    def get_object(self):
        team_id = self.kwargs.get("pk")
        return get_object_or_404(Team, pk=team_id)

class TeamDeleteView(DeleteView):
    model = Team
    template_name = 'teams/delete.html'
    queryset = model.objects.all()

    def get_object(self):
        team_id = self.kwargs.get("pk")
        return get_object_or_404(Team, pk=team_id)
    def get_success_url(self):
        return reverse('teams:index')

def post_comment(request, pk):
    team = get_object_or_404(Team, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comment(author=comment_author,
                              text=comment_text,
                              team=team)
            comment.save()
            return HttpResponseRedirect(
                reverse('teams:detail', args=(pk, )))
    else:
        form = CommentForm()
    context = {'form': form, 'team': team}
    return render(request, 'teams/comment.html', context)

teams/templates/teams/comment.html
{% extends 'base.html' %}

{% block title %}
Comentário
{% endblock title %}

{% block content %}
<h2>Adicionar comentário em {{ team.name }}:</h2>
<form method="POST" action="{% url 'teams:comment' team.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">COMENTAR</button>
    <p><b><big><a href="{% url 'teams:detail' team.id %}">CANCELAR</a></b></big></p>
</form>

{% endblock content %}

teams/templates/teams/create.html
{% extends 'base.html' %}

{% block title %}
Nova equipe
{% endblock title %}

{% block content %}
<h2>Inserir nova equipe</h2>
<form method="POST" action="{% url 'teams:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <p class="form-buttons">
        <button type="submit">
            CRIAR EQUIPE
            <i class="fas fa-plus-circle"></i>
        </button>
        <b><big><a href="{% url 'teams:index' %}">
            <br>CANCELAR
        </a></b></big>
    </p>
</form>

{% endblock content %}

teams/templates/teams/delete.html
{% extends 'base.html' %}

{% block title %}
Excluir equipe
{% endblock title %}

{% block content %}
<form action="{% url 'teams:delete' team.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja excluir a equipe 
        <b><big>{{ team.name }}?</big></b>
    </p>
    <p class="form-buttons">
        <button type="submit">
            CONFIRMAR EXCLUSÃO
            <i class="fas fa-trash-alt"></i>
        </button>
        <b><big><a href="{% url 'teams:detail' team.id %}">
            CANCELAR
        </a></b></big>
    </p>
</form>

{% endblock content %}

teams/templates/teams/detail.html
{% extends 'base.html' %}

{% block title %}
{{ team.name }}
{% endblock title %}

{% block content %}
<h2> {{ team.name }} </h2>
<small>Postado em {{ team.post_date | date:"d M. Y" }}</small>

<section class="dados-da-equipe">
    <div class="logo_unique">
        <img src="{{ team.logo_url }}" alt="Escudo da equipe {{ team.name }}">
    </div>
    <article>
        <p><b>Nome completo da equipe:</b><br>
            {{ team.full_name }} </p>
        <p><b>Ano de fundação:</b><br> 
            {{ team.foundation }}</p>
        <p><b>Cidade sede:</b><br>
            {{ team.base_city }}</p>
        <p><b>País:</b><br>
            {{ team.country }}</p>

        {% if team.competitions.all %}
        <p><b>Competições disputadas:</b><br>
            <ul>
                {% for competition in team.competitions.all|dictsort:"name" %}
                <li><a href="{% url 'competitions:detail' competition.id %}">{{ competition.name }}</a></li>
                {% endfor %}
            </ul>
        {% endif %}
        
        <b>Sobre a equipe:</b>
        <p>{{ team.about|safe }}</p>
    </article>
</section>

<section class="comentarios">
    <hr>
    <header><h3>Comentários</h3></header>

    <table>
        {% if team.comments.all %}
            {% for comment in team.comments.all|dictsortreversed:"post_date" %}
            <tr>
                <td class="col1"><b>{{ comment.author.username }}</b></td>
                <td class="col2"><small>{{ comment.post_date | date:"d/m/y - h:i A" }}</small></td>
                <td class="col3">{{ comment.text }}</td>
            </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td class="comentario-controle">Sem comentários ainda...</td>
                <td></td><td></td>
            </tr>
        {% endif %}
        <tr>
            <td class="comentario-controle"><b><a href="{% url 'teams:comment' team.pk %}">
                Adicionar comentário</a></b></td>
            <td></td><td></td>
        </tr>
    </table>
    <hr>


    <p><b><big><a href="{% url 'teams:update' team.pk %}">
        EDITAR EQUIPE
        <i class="fas fa-edit"></i>
    </a></b></big></p>
    <p><b><big><a href="{% url 'teams:delete' team.pk %}">
        EXCLUIR EQUIPE
        <i class="fas fa-trash-alt"></i>
    </a></b></big></p>
</section>

{% endblock content %}

teams/templates/teams/index.html
{% extends 'base.html' %}

{% block title %}
Equipes
{% endblock title %}

{% block content %}

<form action="{% url 'teams:search' %}" class="busca">
    <input type="text" name="query" id="id_query" placeholder="Buscar por equipes"/>
    <button type="submit">Buscar</button>
</form>

<h2>Todas as Equipes</h2>
<section>
    <p>
        Não encontrou o que estava procurando?
        <i><a href="{% url 'teams:create' %}">
        Clique aqui para adicionar uma nova equipe</a></i>
    </p>
</section>

{% if team_list %}
<section class="cards-grid">
    {% for team in team_list|dictsort:"name" %}
    <a href="{% url 'teams:detail' team.id %}">
        <div class="card_logo">
            <img src="{{ team.logo_url }}" alt="Escudo da equipe {{ team.name }}">
        </div>
        <div>
            {{ team.name }}<br>
            <small>{{ team.country }}</small>
        </div>
    </a>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrada nenhuma equipe.</p>
{% endif %}

{% endblock content %}

teams/templates/teams/search.html
{% extends 'base.html' %}

{% block title %}
Busca por equipe
{% endblock title %}

{% block content %}

<form action="{% url 'teams:search' %}" class="busca">
    <input type="text" name="query" id="id_query" placeholder="Buscar por equipes"/>
    <button type="submit">Buscar</button>
</form>

<h2>Resultados da busca</h2>
<section>
    <p>
        Não encontrou o que estava procurando?
        <i><a href="{% url 'teams:create' %}">
        Clique aqui para adicionar uma nova equipe</a></i>
    </p>
</section>

{% if team_list %}
<section class="cards-grid">
    {% for team in team_list|dictsort:"name" %}
    <a href="{% url 'teams:detail' team.id %}">
        <div class="card_logo">
            <img src="{{ team.logo_url }}" alt="Escudo da equipe {{ team.name }}">
        </div>
        <div>
            {{ team.name }}<br>
            <small>{{ team.country }}</small>
        </div>
    </a>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrada nenhuma equipe.</p>
{% endif %}

{% endblock content %}

teams/templates/teams/update.html
{% extends 'base.html' %}

{% block title %}
Editar equipe
{% endblock title %}

{% block content %}
<h2>Atualizar dados da equipe {{ team.name }}</h2>
<form method="POST" action="{% url 'teams:update' team.id%}">
    {% csrf_token %}
    {{ form.as_p }}

    <p class="form-buttons">
        <button type="submit">
            ATUALIZAR EQUIPE
            <i class="fas fa-edit"></i>
        </button>
        <b><big><a href="{% url 'teams:detail' team.id %}">
            <br>CANCELAR
        </a></b></big>
    </p>
</form>

{% endblock content %}