competitions/urls.py
from django.urls import path

from . import views

app_name = 'competitions'
urlpatterns = [
    path('', views.CompetitionListView.as_view(), name='index'),
    path('<int:pk>/', views.CompetitionDetailView.as_view(), name='detail'),
    path('search/', views.search_competitions, name='search'),
    path('create/', views.CompetitionCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.CompetitionUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.CompetitionDeleteView.as_view(), name='delete'),

]

soccersite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('staticpages.urls')),
    path('teams/', include('teams.urls')),
    path('competitions/', include('competitions.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
    document_root=settings.MEDIA_ROOT)

teams/urls.py
from django.urls import path

from . import views

app_name = 'teams'
urlpatterns = [
    path('', views.TeamListView.as_view(), name='index'),
    path('<int:pk>/', views.TeamDetailView.as_view(), name='detail'), 
    path('search/', views.search_teams, name='search'),
    path('create/', views.TeamCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.TeamUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.TeamDeleteView.as_view(), name='delete'),
    path('<int:pk>/comment/', views.post_comment, name='comment'),
]

competitions/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.urls import reverse

from teams.models import Team

# Create your models here.
class Competition(models.Model):
    "Categorizacao das paginas de equipes"
    post_date    = models.DateTimeField(default = timezone.now)
    name         = models.CharField(max_length=100)
    first_ed     = models.IntegerField()
    logo_url     = models.URLField(max_length=500, null=True)
    region       = models.CharField(max_length=100)
    organization = models.CharField(max_length=100)
    about        = models.TextField(default="")
    teams        = models.ManyToManyField(Team, related_name="competitions", blank=True)

    def get_absolute_url(self):
        return reverse("competitions:detail", kwargs={"pk":self.pk})

    def __str__(self):
        return f'{self.name}'

competitions/forms.py
from django.forms import ModelForm
from .models import Competition
from teams.models import Team

class CompetitionForm(ModelForm):
    class Meta:
        model = Competition
        fields = [
            'name',
            'first_ed',
            'logo_url',
            'region',
            'organization',
            'teams',
            'about'
        ]
        labels = {
            'name': 'Nome da competição',
            'first_ed': 'Primeira edição',
            'logo_url': 'URL do logo',
            'region': 'Região de disputa',
            'organization': 'Organização',
            'teams': 'Equipes participantes',
            'about':'Sobre a competição'
        }
    
    def __init__(self, *args, **kwargs):
        super(CompetitionForm, self).__init__(*args, **kwargs)   
        self.fields['teams'].queryset = Team.objects.order_by('name')

competitions/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, F, fields
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView 

from .models import Competition
from .forms import  CompetitionForm

# Create your views here.

def search_competitions(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        competition_list = Competition.objects.filter(
                                Q(name__icontains=search_term) | 
                                Q(region__icontains=search_term) 
                                )
        context = {"competition_list": competition_list}
    return render(request, 'competitions/search.html', context)

class CompetitionDetailView(DetailView):
    model = Competition
    template_name = 'competitions/detail.html'
    queryset = model.objects.all()
    
    def get_object(self):
        competition_id = self.kwargs.get("pk")
        return get_object_or_404(Competition, pk=competition_id)
    
class CompetitionListView(ListView):
    model = Competition
    template_name = 'competitions/index.html'
    queryset = model.objects.all()

class CompetitionCreateView(CreateView):
    model = Competition
    template_name = 'competitions/create.html'
    form_class = CompetitionForm
    queryset = model.objects.all()
    
    def form_valid(self, form):
        return super().form_valid(form)
    
class CompetitionUpdateView(UpdateView):
    model = Competition
    template_name = 'competitions/update.html'
    form_class = CompetitionForm
    queryset = model.objects.all()

    def form_valid(self, form):
        return super().form_valid(form)
    def get_object(self):
        competition_id = self.kwargs.get("pk")
        return get_object_or_404(Competition, pk=competition_id)

class CompetitionDeleteView(DeleteView):
    model = Competition
    template_name = 'competitions/delete.html'
    queryset = model.objects.all()

    def get_object(self):
        competition_id = self.kwargs.get("pk")
        return get_object_or_404(Competition, pk=competition_id)
    def get_success_url(self):
        return reverse('competitions:index')

competitions/templates/competitions/create.html
{% extends 'base.html' %}

{% block title %}
Nova competição
{% endblock title %}

{% block content %}
<h2>Inserir nova competição</h2>
<form method="POST" action="{% url 'competitions:create' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <p class="form-buttons">
        <button type="submit">
            CRIAR COMPETIÇÃO
            <i class="fas fa-plus-circle"></i>
        </button>
        <b><big><a href="{% url 'competitions:index' %}">
            <br>CANCELAR
        </a></b></big>
    </p>
</form>

{% endblock content %}

competitions/templates/competitions/delete.html
{% extends 'base.html' %}

{% block title %}
Excluir competição
{% endblock title %}

{% block content %}
<form action="{% url 'competitions:delete' competition.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja excluir a competição 
        <b><big>{{ competition.name }}?</big></b>
    </p>
    <p class="form-buttons">
        <button type="submit">
            CONFIRMAR EXCLUSÃO
            <i class="fas fa-trash-alt"></i>
        </button>
        <p><b><big><a href="{% url 'competitions:detail' competition.id %}">
            CANCELAR
        </a></b></big>
    </p>
</form>

{% endblock content %}

competitions/templates/competitions/detail.html
{% extends 'base.html' %}

{% block title %}
{{ competition.name }}
{% endblock title %}

{% block content %}
<h2> {{ competition.name }} </h2>
<small>Postado em {{ competition.post_date | date:"d M. Y" }}</small>

<section class="dados-da-competicao">
    <div class="logo_unique">
        <img id="logo" src="{{ competition.logo_url }}" alt="Logo da competição {{ competition.name }}">
    </div>
    <article>
        <p><b>Região de disputa:</b><br>
            {{ competition.region }} </p>
        <p><b>Primeira edição:</b><br> 
            {{ competition.first_ed }}</p>
        <p><b>Organização:</b><br>
            {{ competition.organization }}</p>
        <b>Sobre a competição:</b>
            <p>{{ competition.about|safe }}</p>
    </article>

    {% if competition.teams.all %}
    <b>Equipes participantes:</b>
    <article class="small-cards-grid">
        {% for team in competition.teams.all|dictsort:"name" %}
        <a href="{% url 'teams:detail' team.id %}">
            <div class="small-card-logo">
                <img src="{{ team.logo_url }}" alt="Escudo da equipe {{ team.name }}">
            </div>
            <div class="small-card-label">
                {{ team.name }}<br>
                <small>{{ team.country }}</small>
            </div>
        </a>
        {% endfor %}
    </article>
    {% endif %}

    <p><b><big><a href="{% url 'competitions:update' competition.pk %}">
        EDITAR COMPETIÇÃO
        <i class="fas fa-edit"></i>
    </a></b></big></p>
    <p><b><big><a href="{% url 'competitions:delete' competition.pk %}">
        EXCLUIR COMPETIÇÃO
        <i class="fas fa-trash-alt"></i>
    </a></b></big></p>
</section>

{% endblock content %}

competitions/templates/competitions/index.html
{% extends 'base.html' %}

{% block title %}
Competições
{% endblock title %}

{% block content %}

<form action="{% url 'competitions:search' %}" class="busca">
    <input type="text" name="query" id="id_query" placeholder="Buscar por competição"/>
    <button type="submit">Buscar</button>
</form>

<h2>Todas as Competições</h2>
<section>
    <p>
        Não encontrou o que estava procurando?
        <i><a href="{% url 'competitions:create' %}">
        Clique aqui para adicionar uma nova competição</a></i>
    </p>

    {% if competition_list %}
    <article class="cards-grid">
        {% for competition in competition_list|dictsort:"name" %}
        <a href="{% url 'competitions:detail' competition.id %}">
            <div class="card_logo">
                <img src="{{ competition.logo_url }}" alt="Logo da competição {{ competition.name }}">
            </div>
            <div>
                {{ competition.name }}<br>
                <small>{{ competition.region }}</small>
            </div>
        </a>
        {% endfor %}
    </article>

    {% else %}
    <p>Não foi encontrada nenhuma competição.</p>
    {% endif %}

</section>


{% endblock content %}

competitions/templates/competitions/search.html
{% extends 'base.html' %}

{% block title %}
Busca por competição
{% endblock title %}

{% block content %}

<form action="{% url 'competitions:search' %}" class="busca">
    <input type="text" name="query" id="id_query" placeholder="Buscar por competição"/>
    <button type="submit">Buscar</button>
</form>

<h2>Resultados da busca</h2>

{% if competition_list %}
<section>
    <p>
        Não encontrou o que estava procurando?
        <i><a href="{% url 'competitions:create' %}">
        Clique aqui para adicionar uma nova competição</a></i>
    </p>
</section>

<section class="cards-grid">
    {% for competition in competition_list|dictsort:"name" %}
    <a href="{% url 'competitions:detail' competition.id %}">
        <div class="card_logo">
            <img src="{{ competition.logo_url }}" alt="Logo da competição {{ competition.name }}">
        </div>
        <div>
            {{ competition.name }}<br>
            <small>{{ competition.region }}</small>
        </div>
    </a>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrada nenhuma competição.</p>
<section>
    <p>
        Não encontrou o que estava procurando?
        <i><a href="{% url 'competitions:create' %}">
        Clique aqui para adicionar uma nova competição</a></i>
    </p>
</section>
{% endif %}

{% endblock content %}

competitions/templates/competitions/update.html
{% extends 'base.html' %}

{% block title %}
Editar competição
{% endblock title %}

{% block content %}
<h2>Atualizar dados da competição {{ competition.name }}</h2>
<form method="POST" action="{% url 'competitions:update' competition.id%}">
    {% csrf_token %}
    {{ form.as_p }}

    <p class="form-buttons">
        <button type="submit">
            ATUALIZAR COMPETIÇÃO
            <i class="fas fa-edit"></i>
        </button>
        <b><big><a href="{% url 'competitions:detail' competition.id %}">
            <br>CANCELAR
        </a></b></big>
    </p>

</form>

{% endblock content %}