competitions/urls.py
from django.urls import path

from . import views

app_name = 'competitions'
urlpatterns = [
    path('', views.CompetitionListView.as_view(), name='index'),
    path('<int:pk>/', views.CompetitionDetailView.as_view(), name='detail'),
    path('search/', views.search_competitions, name='search'),
    path('create/', views.CompetitionCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.CompetitionUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.CompetitionDeleteView.as_view(), name='delete'),

]

soccersite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('staticpages.urls')),
    path('teams/', include('teams.urls')),
    path('competitions/', include('competitions.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
    document_root=settings.MEDIA_ROOT)

teams/urls.py
from django.urls import path

from . import views

app_name = 'teams'
urlpatterns = [
    path('', views.TeamListView.as_view(), name='index'),
    path('<int:pk>/', views.TeamDetailView.as_view(), name='detail'), 
    path('search/', views.search_teams, name='search'),
    path('create/', views.TeamCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.TeamUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.TeamDeleteView.as_view(), name='delete'),
    path('<int:pk>/comment/', views.post_comment, name='comment'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" id="TOP">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} || FIFA
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="shortcut icon" href="{% static 'logo.ico' %}"/>
    <link rel="ICON" href="{% static 'logo.ico' | relURL %}"/>
    <script src="https://kit.fontawesome.com/421827ddfd.js" crossorigin="anonymous"></script>

</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo.svg' %}"> </a>
        <nav id="navegacao-principal" >
            <a href="{% url 'teams:index' %}">
                Equipes
                <i class="fas fa-futbol"></i>
            </a>
            <a href="{% url 'competitions:index' %}">
                Competições
                <i class="fas fa-trophy"></i>
            </a>
            <a href="{% url 'about' %}">
                Sobre
                <i class="fas fa-info-circle"></i>
            </a>
        </ul></nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
        <a href="#TOP" id="scroll-up"><i class="fas fa-angle-double-up fa-2x"></i></a>
    </main>

    <footer id="rodape-principal">
        <small>Copyright 2021 - Henrique Pedro Roschel.</small>
    </footer>
</body>

</html>